# Data Preprocessing Tools

## Importing the libraries

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing the dataset

In [19]:
dataset = pd.read_csv(r"C:\Users\Naveen\Desktop\GitHub\Udemy_ML_course\Part 1 - Data Preprocessing\Data.csv")
dataset.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [20]:
X = dataset.loc[:, ["Country", "Age", "Salary"]]
y = dataset.loc[:, ["Purchased"]]

In [21]:
display(X[:5])
print("--------------------------------------")
display(y[:5])

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN

--------------------------------------

  Purchased
0        No
1       Yes
2        No
3        No
4       Yes

## Taking care of missing data

In [22]:
def Fillna_ContVars(df):
    X = df.select_dtypes(["int", "float"])
    
    for i in X.columns:
        X[i] = X[i].fillna(X[i].median())

    df[X.columns] = X
    return df

In [23]:
Fillna_ContVars(X)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0  61000.0
5   France  35.0  58000.0
6    Spain  38.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

## Encoding categorical data

In [24]:
# One hot-encoding

X = pd.get_dummies(X, drop_first=True).astype(float)

### Encoding the Independent Variable

In [25]:
X

    Age   Salary  Country_Germany  Country_Spain
0  44.0  72000.0              0.0            0.0
1  27.0  48000.0              0.0            1.0
2  30.0  54000.0              1.0            0.0
3  38.0  61000.0              0.0            1.0
4  40.0  61000.0              1.0            0.0
5  35.0  58000.0              0.0            0.0
6  38.0  52000.0              0.0            1.0
7  48.0  79000.0              0.0            0.0
8  50.0  83000.0              1.0            0.0
9  37.0  67000.0              0.0            0.0

### Encoding the Dependent Variable

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
le = LabelEncoder()
y = le.fit_transform(y)
y

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

## Splitting the dataset into the Training set and Test set

In [28]:
from sklearn.model_selection import train_test_split

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3)

In [29]:
display(train_X)
print("-----------------------")
display(train_y)
print("-----------------------")
display(test_X)
print("-----------------------")
display(test_y)
print("-----------------------")

    Age   Salary  Country_Germany  Country_Spain
5  35.0  58000.0              0.0            0.0
3  38.0  61000.0              0.0            1.0
8  50.0  83000.0              1.0            0.0
9  37.0  67000.0              0.0            0.0
2  30.0  54000.0              1.0            0.0
0  44.0  72000.0              0.0            0.0
6  38.0  52000.0              0.0            1.0

-----------------------

array([1, 0, 0, 1, 0, 0, 0])

-----------------------

    Age   Salary  Country_Germany  Country_Spain
7  48.0  79000.0              0.0            0.0
1  27.0  48000.0              0.0            1.0
4  40.0  61000.0              1.0            0.0

-----------------------

array([1, 1, 1])

-----------------------

## Feature Scaling

In [30]:
from sklearn.preprocessing import StandardScaler

In [31]:
std_sc = StandardScaler()

# -------------------------------We don't want to use StandardScaler on dummies or encoded values 
std = StandardScaler()

# For train data
std.fit(train_X.iloc[:, :2])
train_X.iloc[:, :2] = std.transform(train_X.iloc[:, :2])

# For test

test_X.iloc[:, :2] = std.transform(test_X.iloc[:, :2])

In [32]:
display(train_X.head())
print("-----------------------------------")
display(test_X.head())

        Age    Salary  Country_Germany  Country_Spain
5 -0.646904 -0.576380              0.0            0.0
3 -0.143756 -0.281161              0.0            1.0
8  1.868833  1.883777              1.0            0.0
9 -0.311472  0.309277              0.0            0.0
2 -1.485483 -0.970005              1.0            0.0

-----------------------------------

        Age    Salary  Country_Germany  Country_Spain
7  1.533402  1.490152              0.0            0.0
1 -1.988630 -1.560442              0.0            1.0
4  0.191675 -0.281161              1.0            0.0